### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by OliveSonDev**
Assigning to Dragan

### CODE REVIEW

**Comment by aMacDawg** [comment]
👍 Please let me know if you have any questions! Also, you can hit me up directly at @andymac on our dev slack veritonedev.slack.com

**Comment by andymac** [comment]
🧐

**Comment by aMacDawg** [comment]
@andymac , sorry tagged you by accident 😅 -- was referring to my own slack handle. Sorry again, please disregard

**Comment by OliveSonDev** [comment]
Could you invite me to your slack with this email ?
olivesondev@gmail.com

**Comment by aMacDawg** [comment]
> Could you invite me to your slack with this email ?
> [olivesondev@gmail.com](mailto:olivesondev@gmail.com)

invite sent 🎉

**Pull request merged**
